export const UserData = [
  {
    name: "Abhinav Maurya",
    username: "abhinav476",
    post: "Hii Dev.io Community, I'm working on a new project which is a social media plateform but for Developers. Please suggest me some features i can add ?",
    likes: 221,
    comments: 39,
    saved: 11,
  },
  {
    name: "John Doe",
    username: "johndoe123",
    post: "Just finished coding a new feature for my project! Feeling accomplished 💻",
    likes: 145,
    comments: 18,
    saved: 5,
  },
  {
    name: "Jane Smith",
    username: "janesmith456",
    post: "Attended an amazing tech conference today. Learned so much!",
    likes: 312,
    comments: 63,
    saved: 27,
  },
  {
    name: "Alex Patel",
    username: "alexP",
    post: "Excited to announce the launch of our new app! Check it out: www.example.com",
    likes: 412,
    comments: 87,
    saved: 42,
  },
  {
    name: "Emily Brown",
    username: "emilyB",
    post: "Struggling with a bug in my code. Any debugging tips?",
    likes: 76,
    comments: 25,
    saved: 3,
  },
  {
    name: "Rahul gogli",
    username: "rahul3",
    post: "Struggling with a bug in my code. Any debugging tips?",
    likes: 76,
    comments: 25,
    saved: 3,
  },
];
